<?php
return [

    'phone_numbers' => [
        'مكتب محافظة قم' => '025-32941115',
        'مكتب محافظة قزوين' => '028-33689305',
        ' مكتب مقاطعة المركز' => '086-32236753',
        'مكتب مقاطعة مازندران' => '011-32228159',
        'مكتب جزيرة كيش' => '076-44470409',
        'مكتب مقاطعة يزد' => '035-36293637',
        'مكتب مقاطعة أذربيجان الغربية' => '044-42246513',
        'مكتب مقاطعة كوردستان' => '087-33629376',
        'مكتب مقاطعة خوزستان' => '061-33335101',
    ],

    'main' => [
        'title' => 'سقف وافل کیوبوید',
        'status' => '1',
        'meta_keywords' => 'کیوبوید، سقف ، وافل',
        'meta_description' => 'سقف وافل کیوبوید',
    ],
    'about_us' => [
        'introduction' => 'تم تأسيس شركة اسمنت تاواي ، وهي شبكة من النخب العلمية ووكلاء التشغيل ذوي الخبرة ، في عام 2006 بهدف الابتكار والتحسين في صناعة البناء. استنادًا إلى المعرفة الفنية لليوم واستخدام قوتها ، نجحت السلسلة في تصميم وتسجيل وتنفيذ نوع جديد من السقف الخرساني Waffle ، والذي تم تقديمه إلى مجتمع هندسة البناء تحت عنوان Wavefront Ceiling. على مدار العامين الماضيين ، نجح المجمع في تصميم وتنفيذ أكثر من 40 مشروعًا مع بنية تحتية تزيد مساحتها عن 450000 متر مربع. يشير هذا الحجم من تنفيذ سقف كيوبيد والقبول المثير للإعجاب لمجتمع مهندسي البناء وأصحاب العمل إلى تفوقه التقني والاقتصادي.',
        'email' => 'info@cuboid.ir',
        'phone' => '۳۲۹۴۱۱۱۵-۰۲۵',
        'fax' => '009823000000',
        'address' => 'طهران ، الجادة أفريكا ، سابا الجادة ، رقم 42 ، الوحدة 21
021-22020061 ، 021-22016991 ، 021-26207499
021-26210871',
        'longitude' => '000',
        'latitude' => '000',
    ],
    'social_networks' => [
        'linkedin' => 'https://linkedin.com/cuboid.ir',
        'telegram' => 'https://telegram.me/cuboid.ir',
        'google-plus' => 'https://plus.google.com/+cuboid.ir',
        'youtube' => 'https://youtube.com/cuboid.ir',
        'facebook' => 'https://www.facebook.com/cuboid.ir',
        'instagram' => 'https://www.instagram.com/cuboid.ir',
        'twitter' => 'https://twitter.com/cuboid.ir',
        'whatsapp' => 'https://whatsapp.com/cuboid.ir',
    ],

    'user' => [
        'avatar_size' => '500',
        'avatar_width' => '250',
        'avatar_height' => '250',
        'avatar_extension' => 'jpg, jpeg, png',
        'avatar_destination' => 'users/avatar/',
    ],
    'content' => [
        'logo_size' => '1024',
        'logo_width' => '348',
        'logo_height' => '170',
        'logo_extension' => 'jpg, jpeg, png',
        'logo_destination' => 'content/logo/',
        'image_size' => '2048',
        'image_width' => '800',
        'image_height' => '550',
        'image_extension' => 'jpg, jpeg, png',
        'image_destination' => 'content/image/',
    ],
    'page' => [
        'image_size' => '500',
        'image_width' => '400',
        'image_height' => '300',
        'image_extension' => 'jpg, jpeg, png',
        'image_destination' => 'page/image/',
    ],
    'slider' => [
        'image_size' => '2048',
        'image_width' => '1600',
        'image_height' => '755',
        'image_extension' => 'jpg,jpg, jpeg, png',
        'image_destination' => 'slider/image/',
    ],
    'product' => [
        'image_size' => '2048',
        'image_width' => '2000',
        'image_height' => '767',
        'image_extension' => 'jpg, jpeg, png',
        'image_destination' => 'product/image/',
    ],
    'project' => [
        'image_size' => '2048',
        'image_width' => '304',
        'image_height' => '255',
        'image_extension' => 'jpg, jpeg, png',
        'image_destination' => 'project/image/',
    ],
    'gallery' => [
        'image_size' => '500',
        'image_width' => '700',
        'image_height' => '450',
        'image_extension' => 'jpg, jpeg, png',
        'image_destination' => 'gallery/image/',
    ],
    'gallery_item' => [
        'logo_size' => '500',
        'logo_width' => '250',
        'logo_height' => '250',
        'logo_extension' => 'jpg, jpeg, png',
        'logo_destination' => 'gallery_item/logo/',
        'image_size' => '500',
        'image_width' => '700',
        'image_height' => '450',
        'image_extension' => 'jpg, jpeg, png',
        'image_destination' => 'gallery_item/image/',
    ],
    'attachment' => [
        'attachment_size' => '2048',
        'attachment_extension' => 'doc,docx,pdf,zip,rar,txt',
        'attachment_destination' => 'attachment/',
    ],

    'available_langs' => ['fa', 'en', 'ar'],
];
