<?php
return [

    'main' => [
            'title' =>  'سقف وافل کیوبوید',
            'status' =>  '1',
            'meta_keywords' =>  'کیوبوید، سقف ، وافل ',
            'meta_description' =>  'سقف وافل کیوبوید',
        ],
    'about_us' => [
            'introduction' =>  'این متن ازمایشی است',
            'email' =>  'info@cuboid.ir',
            'telegram' =>  'https://telegram.me/cuboid.ir',
            'instagram' =>  'https://www.instagram.com/cuboid.ir',
            'facebook' =>  'https://www.facebook.com/cuboid.ir',
            'google_plus' =>  'https://plus.google.com/+cuboid.ir',
            'twitter' =>  'https://twitter.com/cuboid.ir',
            'phone' =>  '۳۲۹۴۱۱۱۵-۰۲۵',
            'fax' =>  '009823000000',
            'address' =>  'Iran - Tehran',
            'longitude' =>  '000',
            'latitude' =>  '000',
        ],
    'user' => [
            'avatar_size' =>  '500',
            'avatar_width' =>  '250',
            'avatar_height' =>  '250',
            'avatar_extension' =>  'jpg, jpeg, png',
            'avatar_destination' =>  'users/avatar/',
        ],
    'content' => [
            'logo_size' =>  '1024',
            'logo_width' =>  '550',
            'logo_height' =>  '550',
            'logo_extension' =>  'jpg, jpeg, png',
            'logo_destination' =>  'content/logo/',
            'image_size' =>  '2048',
            'image_width' =>  '800',
            'image_height' =>  '550',
            'image_extension' =>  'jpg, jpeg, png',
            'image_destination' =>  'content/image/',
        ],
    'page' => [
            'image_size' =>  '500',
            'image_width' =>  '200',
            'image_height' =>  '278',
            'image_extension' =>  'jpg, jpeg, png',
            'image_destination' =>  'page/image/',
        ],
    'slider' => [
            'image_size' =>  '2048',
            'image_width' =>  '2000',
            'image_height' =>  '767',
            'image_extension' =>  'jpg, jpeg, png',
            'image_destination' =>  'slider/image/',
        ],
    'gallery' => [
            'image_size' =>  '500',
            'image_width' =>  '700',
            'image_height' =>  '450',
            'image_extension' =>  'jpg, jpeg, png',
            'image_destination' =>  'gallery/image/',
        ],
    'gallery_item' => [
            'logo_size' =>  '500',
            'logo_width' =>  '250',
            'logo_height' =>  '250',
            'logo_extension' =>  'jpg, jpeg, png',
            'logo_destination' =>  'gallery_item/logo/',
            'image_size' =>  '500',
            'image_width' =>  '700',
            'image_height' =>  '450',
            'image_extension' =>  'jpg, jpeg, png',
            'image_destination' =>  'gallery_item/image/',
        ],
    'attachment' => [
            'attachment_size' =>  '2048',
            'attachment_extension' =>  'doc,docx,pdf,zip,rar,txt',
            'attachment_destination' =>  'attachment/',
        ],

'available_langs'=>['fa','en','ar'],
];
